name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    name: Check workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Run actionlint
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
