name: Dependency Review

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Scan dependency changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: Dependency Review (Swift needs Package.resolved)
        if: ${{ hashFiles('Package.resolved') != '' }}
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          fail-on-severity: high

      - name: Skip Dependency Review
        if: ${{ hashFiles('Package.resolved') == '' }}
        run: |
          echo "Skipping dependency review: Package.resolved not present in repository."
