name: OpenSSF Scorecard

on:
  push:
    branches: [ "master" ]
  branch_protection_rule:
  schedule:
    - cron: "0 4 * * 1"

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.3
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif
